#! /usr/bin/sh

count=1

while [ $count -le 90 ]
do
clean
echo getinc.f
f77 getinc.f 
a.out $count

KD=/zemo2/jiaxj/igcm
EXPID=ForeExp                 # Experiment identifier.
EXPDIR=/zemo2/jiaxj/Internal/Prediction/Test/$EXPID          # Experiment directory.
EXEC=../../test.exe
[ ! -d $EXPDIR ]   &&   mkdir -p $EXPDIR
#
    ln  -s data  fort.7
    ln  -s $KD/data/MG64JG16.orog.b  fort.18
    ln  -s $KD/data/MG64JG16.mask.b  fort.19

    ln  -s /D1/hlin/igcm/data/FORCE_DJF_ave.dat_crtd  fort.13
    ln  -s $EXPDIR/OUTpred_$count.dat  fort.9
    $EXEC
	
    count=`expr $count + 1`
clean
done

