#! /usr/bin/sh

count=1

while [ $count -le 2 ]
do
clean
echo 2getper.f
f77 2getper.f 
a.out $count

echo 2getper.prog
sh 2getper.prog
clean

echo 3getinc.f
f77 3getinc.f
a.out $count
mv OUTpred_inc.dat OUTpred_inc$count.dat 

echo 3getinc.prog
#####################
KD=/zemo2/jiaxj/igcm
EXPID=ForeExp                 # Experiment identifier.
EXPDIR=/zemo2/jiaxj/Internal/Prediction/Test/$EXPID          # Experiment directory.
EXEC=../test.exe
############################################# UPDATE DIRECTIVES.
[ ! -d $EXPDIR ]   &&   mkdir -p $EXPDIR
#
    ln  -s data  fort.7
    ln  -s $KD/data/MG64JG16.orog.b  fort.18
    ln  -s $KD/data/MG64JG16.mask.b  fort.19

    ln  -s /D1/hlin/igcm/data/FORCE_DJF_ave.dat_crtd  fort.13
    ln  -s $EXPDIR/OUTpred_$count.dat  fort.9
#
    $EXEC

    count=`expr $count + 1`
    rm fort.10 fort.13 fort.9
clean
done
clean

